package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String docName;
	private java.util.List<java.math.BigDecimal> footNoteCodes;

	private java.lang.String documentENname;

	private java.lang.String documentDEName;

	private java.lang.String documentITName;

	private java.lang.String documentFRName;

	private java.lang.String proofOfExistence;

	public Document() {
	}

	public java.lang.String getDocName() {
		return this.docName;
	}

	public void setDocName(java.lang.String docName) {
		this.docName = docName;
	}

	public java.util.List<java.math.BigDecimal> getFootNoteCodes() {
		return this.footNoteCodes;
	}

	public void setFootNoteCodes(
			java.util.List<java.math.BigDecimal> footNoteCodes) {
		this.footNoteCodes = footNoteCodes;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Document{docName=").append(docName);
		sb.append(", footNoteCodes=").append(footNoteCodes);
		sb.append('}');
		return sb.toString();
	}

	public java.lang.String getDocumentENname() {
		return this.documentENname;
	}

	public void setDocumentENname(java.lang.String documentENname) {
		this.documentENname = documentENname;
	}

	public java.lang.String getDocumentDEName() {
		return this.documentDEName;
	}

	public void setDocumentDEName(java.lang.String documentDEName) {
		this.documentDEName = documentDEName;
	}

	public java.lang.String getDocumentITName() {
		return this.documentITName;
	}

	public void setDocumentITName(java.lang.String documentITName) {
		this.documentITName = documentITName;
	}

	public java.lang.String getDocumentFRName() {
		return this.documentFRName;
	}

	public void setDocumentFRName(java.lang.String documentFRName) {
		this.documentFRName = documentFRName;
	}

	public java.lang.String getProofOfExistence() {
		return this.proofOfExistence;
	}

	public void setProofOfExistence(java.lang.String proofOfExistence) {
		this.proofOfExistence = proofOfExistence;
	}

	public Document(java.lang.String docName,
			java.util.List<java.math.BigDecimal> footNoteCodes,
			java.lang.String documentENname, java.lang.String documentDEName,
			java.lang.String documentITName, java.lang.String documentFRName,
			java.lang.String proofOfExistence) {
		this.docName = docName;
		this.footNoteCodes = footNoteCodes;
		this.documentENname = documentENname;
		this.documentDEName = documentDEName;
		this.documentITName = documentITName;
		this.documentFRName = documentFRName;
		this.proofOfExistence = proofOfExistence;
	}

}