package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentPojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DocumentPojo() {
    }




}