package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimpleWrapper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public SimpleWrapper() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public SimpleWrapper(java.lang.String name) {
		this.name = name;
	}

}